### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ghost** [chykcha3/micro-plugin-latex#1]
It is not possible to install the plugin using repo.json, I believe it must be because the version Url is not the one that contains the plugin's zip file, it could be resolved by creating a tag through git and pushing it to github so the zip url can be found at https://github.com/chykcha3/micro-plugin-latex/archive/<version\>.zip.

It would basically be the commands below but see the links for more details:
```sh
git tag \
  -a "0.4.2"         # version \
  -m "Release 0.4.2" # message
git push --tags  # publish the tags

```

## How to Test? 

To test the installation, follow the steps below:

### Settings

Add this repo as a **pluginrepos** option in the
**~/.config/micro/settings.json** file
(it is necessary to restart the micro after this change):

```json
  "pluginrepos": [
    "https://raw.githubusercontent.com/chykcha3/micro-plugin-latex/main/repo.json"
]
```

### Install

In your micro editor press **Ctrl-e** and run command:

```
> plugin install latex-plugin
```

or run in your shell

```sh
micro -plugin install latex-plugin
```

---

Refs:
- https://git-scm.com/book/en/v2/Git-Basics-Tagging
- https://docs.github.com/en/desktop/managing-commits/managing-tags-in-github-desktop

**Comment by chykcha3** [comment]
Thank you for the feedback and provided guidance!
I didn't consider this plugin ready enough to add a possibility to download via Micro's built-in plugin manager. Although I changed my mind, if it make sense for someone then why not.

I added tags and now plugin could be installed the way you described.
Please, notice that the name of the plugin is changed a bit, because Micro's built-in plugin manager has an issue with plugins having a `-` in their name.

So now `micro -plugin install latexplugin` should work as installation command (after adding the repo).
I would highly appreciate if you test it and report does it work or not.
